### PR TITLE
Layout fixes & new colors

### PR DESCRIPTION
**Pull request by RobVer**
previous results side menu on results tab is now fixed

### CODE REVIEW

**Comment by aleks-24** [comment]
Thank you for submitting your pull request

**Review by aleks-24 — DISMISSED** [review]
"Some small issues" -Yme
XML code is still here
Very nice if you ignore the bad things.

**Review by 6950167 — CHANGES_REQUESTED** [review]
got some errors. Previous errors in results still not fixed

**Comment by r2dvos** [comment]
this **does** sucks

**Comment by 6950167** [comment]
tfoe
________________________________
Van: r2dvos ***@***.***>
Verzonden: dinsdag 24 mei 2022 13:04
Aan: TheMinefreak23/fair-rec-kit-app ***@***.***>
CC: Jong, Y.M. de (Yme) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [TheMinefreak23/fair-rec-kit-app] Layout fixes & new colors (PR #105)


this sucks

**Comment by aleks-24** [comment]
Hahaha yes

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mendoxei** [comment]
willem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by 6950167** [comment]
ff stil
________________________________
Van: Lancelot ***@***.***>
Verzonden: dinsdag 24 mei 2022 13:10
Aan: TheMinefreak23/fair-rec-kit-app ***@***.***>
CC: Jong, Y.M. de (Yme) ***@***.***>; Assign ***@***.***>
Onderwerp: Re: [TheMinefreak23/fair-rec-kit-app] Layout fixes & new colors (PR #105)


willem

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by aleks-24** [comment]
Jongens dit lijkt me niet helemaal de bedoeling.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Review by 6950167 — APPROVED** [review]
Works now. Still no scrolling tho

**Pull request merged**
