### PR TITLE
Result format multiset

### PR DESCRIPTION
**Pull request by OGKushper**
Changes to result-by-id and the data format template.
Multisets should now be correctly handled and put in the correct format so that the formatter can read it correctly.
changed format template to reflect changes.

### CODE REVIEW

**Review by DiedevanderHoorn — CHANGES_REQUESTED** [review]
I still get errors, I sent them in discord & please add comments to your code :)

**Comment by mendoxei** [comment]
Yo I fixed a keyerror and pushed it to the branch (the backend uses "recommender_system" rather than "recommender_approach", according to the txt file). That makes it work though! 

One problem, not all metrics show up (i think you might need to iterate over something?). When I select two datasets the metrics only show up for the second one.
(EDIT: my bad , the mock metrics show up for the first table, the true metrics in the second one)
image
image

**Review by mendoxei — APPROVED** [review]
yeah buddy!
amorbius

**Review by DiedevanderHoorn — APPROVED** [review]
It works now, very nice!

**Pull request merged**
