### PR TITLE
User recommendation tables finished

### PR DESCRIPTION
**Pull request by 6950167**
(I hope)

### CODE REVIEW

**Review by DiedevanderHoorn — CHANGES_REQUESTED** [review]
Rating always shows, independent of the show/hide button. Names for columns could be formatted a bit better.

**Comment by mendoxei** [comment]
image
you missed these requireds xD

**Review by DiedevanderHoorn — APPROVED** [review]
Looks good! One minor detail, usually the asterisk for things that are required is red, so would be good if you could arrange that :)

**Review by aleks-24 — COMMENTED** [review]
nice

**Pull request merged**
