### PR TITLE
Backend link: support new thread experiment system

### PR DESCRIPTION
**Pull request by mendoxei**
- running **one experiment at a time** now works with the new version of the lib
- reworked queue system, uses long polling now
- refactored tab switching to store (global state)
- queue spinner now makes sense 
- tried to change the b-tab style

### CODE REVIEW

**Review by DiedevanderHoorn — CHANGES_REQUESTED** [review]
Does not work for me, new results don't show up in the UI

**Review by 6950167 — CHANGES_REQUESTED** [review]
Completely breaks my server component. 10/10 would commit again

**Comment by mendoxei** [comment]
> Completely breaks my server component. 10/10 would commit again

if it doesn't work now i'll _commit_ something else.

**Review by aleks-24 — CHANGES_REQUESTED** [review]
metrics dont work, results bad

**Review by aleks-24 — APPROVED** [review]
Who will believe my verse in time to come
If it were filled with your most high deserts?
Though yet heaven knows it is but as a tomb
Which hides your life, and shows not half your parts:
If I could write the beauty of your eyes,
And in fresh numbers number all your graces,
The age to come would say this poet lies,
Such heavenly touches ne'er touched earthly faces.
So should my papers (yellowed with their age)
Be scorned, like old men of less truth than tongue,
And your true rights be termed a poet's rage,
And stretched metre of an antique song.
But were some child of yours alive that time,
You should live twice in it, and in my rhyme.

**Pull request closed without merging**
